"""workspaces baseline

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 23:17:49.855583
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=128), nullable=True),
    sa.Column('personal_user_id', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('data_key', sa.Text(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personal_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id'),
    sa.UniqueConstraint('personal_user_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('avatar_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('avatar_id', sa.String(length=120), nullable=False),
    sa.Column('avatar_name', sa.String(length=180), nullable=False),
    sa.Column('avatar_type', sa.String(length=32), nullable=False),
    sa.Column('avatar_preview_url', sa.Text(), nullable=False),
    sa.Column('voice_id', sa.String(length=120), nullable=False),
    sa.Column('voice_name', sa.String(length=180), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('heygen_video_id', sa.String(length=120), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avatar_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avatar_videos_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avatar_videos_heygen_video_id'), ['heygen_video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_avatar_videos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_avatar_videos_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('cliq_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('chat_type', sa.String(length=64), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'chat_id', name='uq_cliq_chat')
    )
    with op.batch_alter_table('cliq_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliq_chats_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliq_chats_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('cliq_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=128), nullable=False),
    sa.Column('chat_name', sa.String(length=256), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('sender', sa.String(length=128), nullable=False),
    sa.Column('sender_id', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('relevant', sa.Boolean(), nullable=False),
    sa.Column('relevance_reasons', sa.JSON(), nullable=False),
    sa.Column('ticket_keys', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'chat_id', 'message_id', name='uq_cliq_msg')
    )
    with op.batch_alter_table('cliq_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliq_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliq_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliq_messages_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('codebase_asks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codebase_asks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codebase_asks_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('codebase_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('docs_excerpt', sa.Text(), nullable=False),
    sa.Column('tree', sa.Text(), nullable=False),
    sa.Column('doc_paths', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codebase_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codebase_modules_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_codebase_modules_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_codebase_modules_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('codebase_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('commit_at', sa.String(length=64), nullable=False),
    sa.Column('commit_message', sa.String(length=512), nullable=False),
    sa.Column('ahead', sa.Integer(), nullable=False),
    sa.Column('behind', sa.Integer(), nullable=False),
    sa.Column('module_count', sa.Integer(), nullable=False),
    sa.Column('pulled', sa.Boolean(), nullable=False),
    sa.Column('pull_error', sa.Text(), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('recent_commits', sa.JSON(), nullable=False),
    sa.Column('live_base', sa.String(length=128), nullable=False),
    sa.Column('live_summary', sa.Text(), nullable=False),
    sa.Column('live_commits', sa.JSON(), nullable=False),
    sa.Column('live_files', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codebase_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codebase_snapshots_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_codebase_snapshots_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('competitor_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('ask_eng', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.Column('raw_excerpt', sa.Text(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_signals_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_signals_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_signals_seen_at'), ['seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_signals_starred'), ['starred'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_signals_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=False),
    sa.Column('changelog_url', sa.String(length=512), nullable=False),
    sa.Column('blog_url', sa.String(length=512), nullable=False),
    sa.Column('pricing_url', sa.String(length=512), nullable=False),
    sa.Column('g2_url', sa.String(length=512), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_competitor_slug')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitors_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secrets', sa.Text(), nullable=False),
    sa.Column('secret_hints', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'name', name='uq_connection')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('copilot_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('results_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_audit_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copilot_audit_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('copilot_plans',
    sa.Column('parent_plan_id', sa.Integer(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('ticket_keys', sa.JSON(), nullable=False),
    sa.Column('people', sa.JSON(), nullable=False),
    sa.Column('image_ids', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('epics', sa.JSON(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('needs_confirm', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_plans_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('copilot_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turns', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_threads_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('match_reason', sa.String(length=256), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correlations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correlations_issue_key'), ['issue_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_correlations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('daily_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('learning', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_notes_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_notes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_notes_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standup_id', sa.Integer(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('signal_detection', sa.Float(), nullable=False),
    sa.Column('prioritization', sa.Float(), nullable=False),
    sa.Column('grounding', sa.Float(), nullable=False),
    sa.Column('actionability', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('noise', sa.Float(), nullable=False),
    sa.Column('hallucination', sa.Float(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_standup_id'), ['standup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('git_stashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('git_stashes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_git_stashes_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('hidden_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_key', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'card_key', name='uq_hidden_card_key')
    )
    with op.batch_alter_table('hidden_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hidden_cards_card_key'), ['card_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_hidden_cards_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('issue_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=32), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('from_value', sa.Text(), nullable=False),
    sa.Column('to_value', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('noisy', sa.Boolean(), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_changes_issue_key'), ['issue_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_changes_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('jira_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=32), nullable=False),
    sa.Column('jira_id', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('status_category', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('assignee', sa.String(length=128), nullable=False),
    sa.Column('assignee_id', sa.String(length=64), nullable=False),
    sa.Column('creator', sa.String(length=128), nullable=False),
    sa.Column('labels', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('comments_json', sa.JSON(), nullable=False),
    sa.Column('changelog_json', sa.JSON(), nullable=False),
    sa.Column('extra_json', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'issue_key', name='uq_jira_issue_key')
    )
    with op.batch_alter_table('jira_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jira_issues_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jira_issues_issue_key'), ['issue_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jira_issues_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jira_issues_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('library_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extraction_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'file_id', name='uq_library_file')
    )
    with op.batch_alter_table('library_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_documents_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_surface'), ['surface'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('market_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('affects_roadmap', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.Column('raw_excerpt', sa.Text(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_signals_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_signals_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_signals_seen_at'), ['seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_signals_starred'), ['starred'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_signals_watch_id'), ['watch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_signals_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('market_watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_watches_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_watches_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('marketing_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_key', sa.String(length=200), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('feature_revision', sa.Integer(), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=160), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'run_key', name='uq_marketing_campaign_run_key')
    )
    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_campaigns_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_campaigns_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('marketing_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('identity', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=280), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('benefit', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=False),
    sa.Column('end_date', sa.String(length=32), nullable=False),
    sa.Column('sheet_status', sa.String(length=64), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('video', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'identity', name='uq_marketing_feature_identity')
    )
    with op.batch_alter_table('marketing_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_features_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('marketing_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('source_sha', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'fingerprint', name='uq_marketing_scan_fingerprint')
    )
    with op.batch_alter_table('marketing_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_scans_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_membership')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('parity_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('epic_key', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_parity_name')
    )
    with op.batch_alter_table('parity_capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parity_capabilities_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('jira_account_id', sa.String(length=128), nullable=False),
    sa.Column('cliq_user_id', sa.String(length=128), nullable=False),
    sa.Column('cliq_chat_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('team', sa.String(length=80), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pipeline_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'pipeline_id', name='uq_pipeline_config')
    )
    with op.batch_alter_table('pipeline_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_configs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('jira_count', sa.Integer(), nullable=False),
    sa.Column('cliq_count', sa.Integer(), nullable=False),
    sa.Column('relevant_cliq_count', sa.Integer(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('insight_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('dead_letter', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pm_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('issue_key', sa.String(length=32), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pm_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pm_insights_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pm_insights_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pm_insights_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('prds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('service', sa.String(length=128), nullable=False),
    sa.Column('issue_key', sa.String(length=32), nullable=False),
    sa.Column('issue_keys', sa.JSON(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prds_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pricing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_snapshots_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('prototype_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prototype_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prototype_id', 'path', name='uq_prototype_path')
    )
    with op.batch_alter_table('prototype_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prototype_files_prototype_id'), ['prototype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prototype_files_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('prototype_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prototype_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prototype_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prototype_messages_prototype_id'), ['prototype_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prototype_messages_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('prototypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prototypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prototypes_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('release_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('merged_at', sa.String(length=64), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=False),
    sa.Column('drive_file_id', sa.String(length=128), nullable=False),
    sa.Column('drive_link', sa.String(length=512), nullable=False),
    sa.Column('extraction', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'branch', 'sha', name='uq_release_branch_sha')
    )
    with op.batch_alter_table('release_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_jobs_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('release_notes_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=False),
    sa.Column('emailed_to', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_notes_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_notes_jobs_commit_sha'), ['commit_sha'], unique=False)
        batch_op.create_index(batch_op.f('ix_release_notes_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('release_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('internal_update', sa.Text(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=False),
    sa.Column('newsletter', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_packs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('remote_url', sa.String(length=1024), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=200), nullable=False),
    sa.Column('product_branch', sa.String(length=200), nullable=False),
    sa.Column('release_pattern', sa.String(length=200), nullable=False),
    sa.Column('merge_format', sa.String(length=24), nullable=False),
    sa.Column('path_scopes', sa.JSON(), nullable=False),
    sa.Column('ui_path', sa.String(length=512), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetch_status', sa.String(length=24), nullable=False),
    sa.Column('last_fetch_error', sa.Text(), nullable=False),
    sa.Column('branches_cache', sa.JSON(), nullable=False),
    sa.Column('indexed_branches', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_repository_name')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('months', sa.JSON(), nullable=False),
    sa.Column('month_labels', sa.JSON(), nullable=False),
    sa.Column('epics', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmaps_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('pipeline_id', sa.String(length=64), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('started_by', sa.String(length=256), nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('cost', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('worker_pid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_claim', ['status', 'lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_pipeline_id'), ['pipeline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('standups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('needs_attention', sa.JSON(), nullable=False),
    sa.Column('at_risk', sa.JSON(), nullable=False),
    sa.Column('completed', sa.JSON(), nullable=False),
    sa.Column('team_signals', sa.JSON(), nullable=False),
    sa.Column('todays_actions', sa.JSON(), nullable=False),
    sa.Column('bugs', sa.JSON(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('wallet_requests', sa.JSON(), nullable=False),
    sa.Column('long_pending', sa.JSON(), nullable=False),
    sa.Column('week_actions', sa.JSON(), nullable=False),
    sa.Column('this_week', sa.JSON(), nullable=False),
    sa.Column('other_actions', sa.JSON(), nullable=False),
    sa.Column('cliq_briefing', sa.JSON(), nullable=False),
    sa.Column('dev_load', sa.JSON(), nullable=False),
    sa.Column('monday_plan', sa.JSON(), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standups_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standups_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standups_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_standups_run_id'))

    op.drop_table('standups')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_runs_parent_run_id'))
        batch_op.drop_index(batch_op.f('ix_runs_kind'))
        batch_op.drop_index(batch_op.f('ix_runs_created_at'))
        batch_op.drop_index('ix_runs_claim')

    op.drop_table('runs')
    with op.batch_alter_table('roadmaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmaps_workspace_id'))

    op.drop_table('roadmaps')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_workspace_id'))

    op.drop_table('repositories')
    with op.batch_alter_table('release_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_packs_workspace_id'))

    op.drop_table('release_packs')
    with op.batch_alter_table('release_notes_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_notes_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_release_notes_jobs_commit_sha'))

    op.drop_table('release_notes_jobs')
    with op.batch_alter_table('release_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_release_jobs_repository_id'))

    op.drop_table('release_jobs')
    with op.batch_alter_table('prototypes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prototypes_workspace_id'))

    op.drop_table('prototypes')
    with op.batch_alter_table('prototype_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prototype_messages_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_prototype_messages_prototype_id'))

    op.drop_table('prototype_messages')
    with op.batch_alter_table('prototype_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prototype_files_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_prototype_files_prototype_id'))

    op.drop_table('prototype_files')
    with op.batch_alter_table('pricing_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_pricing_snapshots_competitor_id'))

    op.drop_table('pricing_snapshots')
    with op.batch_alter_table('prds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prds_workspace_id'))

    op.drop_table('prds')
    with op.batch_alter_table('pm_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pm_insights_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_pm_insights_type'))
        batch_op.drop_index(batch_op.f('ix_pm_insights_run_id'))

    op.drop_table('pm_insights')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_workspace_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('pipeline_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_configs_workspace_id'))

    op.drop_table('pipeline_configs')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_workspace_id'))

    op.drop_table('people')
    with op.batch_alter_table('parity_capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parity_capabilities_workspace_id'))

    op.drop_table('parity_capabilities')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('marketing_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_scans_workspace_id'))

    op.drop_table('marketing_scans')
    with op.batch_alter_table('marketing_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_features_workspace_id'))

    op.drop_table('marketing_features')
    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_campaigns_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_campaigns_feature_id'))

    op.drop_table('marketing_campaigns')
    with op.batch_alter_table('market_watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_watches_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_market_watches_category'))

    op.drop_table('market_watches')
    with op.batch_alter_table('market_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_signals_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_market_signals_watch_id'))
        batch_op.drop_index(batch_op.f('ix_market_signals_starred'))
        batch_op.drop_index(batch_op.f('ix_market_signals_seen_at'))
        batch_op.drop_index(batch_op.f('ix_market_signals_content_hash'))
        batch_op.drop_index(batch_op.f('ix_market_signals_category'))

    op.drop_table('market_signals')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_surface'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_run_id'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('library_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_documents_workspace_id'))

    op.drop_table('library_documents')
    with op.batch_alter_table('jira_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jira_issues_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_jira_issues_updated_at'))
        batch_op.drop_index(batch_op.f('ix_jira_issues_issue_key'))
        batch_op.drop_index(batch_op.f('ix_jira_issues_archived_at'))

    op.drop_table('jira_issues')
    with op.batch_alter_table('issue_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_changes_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_issue_changes_issue_key'))

    op.drop_table('issue_changes')
    with op.batch_alter_table('hidden_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hidden_cards_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_hidden_cards_card_key'))

    op.drop_table('hidden_cards')
    with op.batch_alter_table('git_stashes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_git_stashes_workspace_id'))

    op.drop_table('git_stashes')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_standup_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('daily_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_notes_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_daily_notes_kind'))
        batch_op.drop_index(batch_op.f('ix_daily_notes_day'))

    op.drop_table('daily_notes')
    with op.batch_alter_table('correlations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correlations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_correlations_issue_key'))

    op.drop_table('correlations')
    with op.batch_alter_table('copilot_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_threads_workspace_id'))

    op.drop_table('copilot_threads')
    with op.batch_alter_table('copilot_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_plans_workspace_id'))

    op.drop_table('copilot_plans')
    with op.batch_alter_table('copilot_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_audit_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_copilot_audit_plan_id'))

    op.drop_table('copilot_audit')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_connections_provider'))

    op.drop_table('connections')
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_competitors_slug'))

    op.drop_table('competitors')
    with op.batch_alter_table('competitor_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_signals_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_signals_starred'))
        batch_op.drop_index(batch_op.f('ix_competitor_signals_seen_at'))
        batch_op.drop_index(batch_op.f('ix_competitor_signals_content_hash'))
        batch_op.drop_index(batch_op.f('ix_competitor_signals_competitor_id'))

    op.drop_table('competitor_signals')
    with op.batch_alter_table('codebase_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codebase_snapshots_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_codebase_snapshots_repository_id'))

    op.drop_table('codebase_snapshots')
    with op.batch_alter_table('codebase_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codebase_modules_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_codebase_modules_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_codebase_modules_name'))

    op.drop_table('codebase_modules')
    with op.batch_alter_table('codebase_asks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codebase_asks_workspace_id'))

    op.drop_table('codebase_asks')
    with op.batch_alter_table('cliq_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliq_messages_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_cliq_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_cliq_messages_chat_id'))

    op.drop_table('cliq_messages')
    with op.batch_alter_table('cliq_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliq_chats_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_cliq_chats_chat_id'))

    op.drop_table('cliq_chats')
    with op.batch_alter_table('avatar_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatar_videos_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_avatar_videos_status'))
        batch_op.drop_index(batch_op.f('ix_avatar_videos_heygen_video_id'))
        batch_op.drop_index(batch_op.f('ix_avatar_videos_feature_id'))

    op.drop_table('avatar_videos')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    op.drop_table('workspaces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
